export const strings = {
  br: {
    appName: 'Omniapp',
    stringName: 'br',
    stringLabel: 'Português (Brasil)',
    privacy: 'Privacidade',
    terms: 'Termos',
    allRighsReserveds: 'Todos os direitos reservados',
    createdBy: 'Criado por',
    loginTitle: 'Faça seu Login',
    loginWelcome:
      'Bem-vindo(a) de volta! Preparade-se para embarcar em mais uma jornada épica. Faça login e vamos começar.',
    enterEmailValid: 'Digite um email válido',
    password: 'Senha',
    passwordInvalidText: 'Sua senha precisa ter pelo menos 8 carateres',
    inputPasswordPlaceholder: 'Mínimo de 8 caracteres',
    forgotPassword: 'Esqueceu a senha?',
    enter: 'Entrar',
    or: 'ou',
    signUp: 'Cadastrar',
    signUpTitle: 'Faça seu cadastro',
    signUpWelcome:
      'Junte-se a nós em uma jornada épica! Registre-se agora para começar a sua aventura.',
    name: 'Nome',
    enterNameValid: 'Seu nome precisa ter pelo menos 2 caracteres',
    surname: 'Sobrenome',
    alreadyHaveAccount: 'Já possuo uma conta',
    nickname: 'Nome de usuário',
    enterNicknameValid: 'Seu nome de usuário precisa ser único. (. _ - @)',
    emailAlreadyInUse: 'Email já está em uso',
    nicknameAlreadyInUse: 'Nome de usuário já está em uso',
    nicknameOrEmail: 'Email ou nome de usuário',
    enterEmailOrNicknameValid: 'Digite um email ou nome de usuário válido',
    userNotFound: 'Usuário não cadastrado',
    passwordIncorrect: 'Senha está incorreta',
    feed: 'Feed',
    search: 'Pesquisa',
    files: 'Arquivos',
    doesNotHaveFiles: 'Você não possui nenhum arquivo',
    create: 'Criar',
    start: 'Começar',
    createPlaceholderAlt: 'Arquivo de imagem',
    about: 'Sobre',
    textRichPlaceholder: 'Conteúdo aqui...',
  },
  en: {
    appName: 'Omniapp',
    stringName: 'en',
    stringLabel: 'English',
    privacy: 'Privacy',
    terms: 'Terms',
    allRighsReserveds: 'All rights reserved',
    createdBy: 'Created by',
    loginTitle: 'Log In',
    loginWelcome:
      "Welcome back! Get ready to embark on another epic journey. Log in and let's get started.",
    enterEmailValid: 'Enter a valid email',
    password: 'Password',
    passwordInvalidText: 'Your password must be at least 8 characters long',
    inputPasswordPlaceholder: 'Minimum of 8 characters',
    forgotPassword: 'Forgot password?',
    enter: 'Enter',
    or: 'or',
    signUp: 'Sign Up',
    signUpTitle: 'Sign Up',
    signUpWelcome: 'Join us on an epic journey! Register now to start your adventure.',
    name: 'Name',
    enterNameValid: 'Your name must be at least 2 characters long',
    surname: 'Surname',
    alreadyHaveAccount: 'Already have an account',
    nickname: 'Username',
    enterNicknameValid: 'Your username must be unique. (. _ - @)',
    emailAlreadyInUse: 'Email is already in use',
    nicknameAlreadyInUse: 'Username is already in use',
    nicknameOrEmail: 'Email or username',
    enterEmailOrNicknameValid: 'Enter a valid email or username',
    userNotFound: 'User not found',
    passwordIncorrect: 'Incorrect password',
  },
  es: {
    appName: 'Omniapp',
    stringName: 'es',
    stringLabel: 'Español',
    privacy: 'Privacidad',
    terms: 'Términos',
    allRighsReserveds: 'Todos los derechos reservados',
    createdBy: 'Creado por',
    loginTitle: 'Iniciar sesión',
    loginWelcome:
      '¡Bienvenido de nuevo! Prepárate para embarcarte en otra aventura épica. Inicia sesión y comencemos.',
    enterEmailValid: 'Ingresa un correo electrónico válido',
    password: 'Contraseña',
    passwordInvalidText: 'Tu contraseña debe tener al menos 8 caracteres',
    inputPasswordPlaceholder: 'Mínimo de 8 caracteres',
    forgotPassword: '¿Olvidaste tu contraseña?',
    enter: 'Ingresar',
    or: 'o',
    signUp: 'Registrarse',
    signUpTitle: 'Registrarse',
    signUpWelcome:
      '¡Únete a nosotros en una aventura épica! Regístrate ahora para comenzar tu aventura.',
    name: 'Nombre',
    enterNameValid: 'Tu nombre debe tener al menos 2 caracteres',
    surname: 'Apellido',
    alreadyHaveAccount: 'Ya tengo una cuenta',
    nickname: 'Nombre de usuario',
    enterNicknameValid: 'Tu nombre de usuario debe ser único. (. _ - @)',
    emailAlreadyInUse: 'El correo electrónico ya está en uso',
    nicknameAlreadyInUse: 'El nombre de usuario ya está en uso',
    nicknameOrEmail: 'Correo electrónico o nombre de usuario',
    enterEmailOrNicknameValid: 'Ingresa un correo electrónico o nombre de usuario válido',
    userNotFound: 'Usuario no encontrado',
    passwordIncorrect: 'Contraseña incorrecta',
  },
};
